repos:
  - repo: <https://github.com/pre-commit/pre-commit-hooks>
    rev: v3.2.0
    hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-filesInstall the hooks
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
      - id: clang-format
        files: \.(c|cpp|h|hpp)$
        args: [--style=google]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/mvdan/sh
    rev: v3.4.0
    hooks:
      - id: shfmt
        args: ["-i", "4"]

  - repo: https://github.com/cheshirekow/cmake_format
    rev: 0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [cmake_format==0.6.13]

  - repo: <https://github.com/commitizen-tools/commitizen>
    rev: v1.17.0
    hooks:
      - id: commitizen
        args: ["--hook-stage", "commit-msg"]
        description: "A tool for writing conventional commits."

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        files: \.py$
        args: [--line-length=88]
        exclude: ^\s*#
        additional_dependencies: [black==23.1.0]
        description: "Black is the uncompromising Python code formatter."
      - id: cppcheck
        name: cppcheck
        entry: cppcheck
        language: system
        types_or: [c, c++]
        files: \.(c|cpp|h|hpp)$
#         args: [--error-exitcode=1, --enable=all]
        args: [--error-exitcode=1, --inline-suppr, --inconclusive, --force, --enable=warning,performance,portability,style,information,missingInclude]
#         args: [--enable=all, --error-exitcode=1, --suppress=missingIncludeSystem, --suppress=unusedFunction, --suppress=duplicateExpression]
        description: "Cppcheck is a static analysis tool for C/C++ code."
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        types_or: [c, c++]
        files: \.(c|cpp|h|hpp)$
        args: [-i]
        description: "ClangFormat is a tool to format C/C++/Obj-C code."

